base_dir: /gpfs/data/fs71254/schirni/NeuralBD_variable_psf_failed
data:
  type: 'GREGOR'
  data_path: '/gpfs/data/fs71254/schirni/Level1_Files/hifi_20191019_082115_sd.fts'
  n_images: 50
  pixel_per_ds: 511.5
  x_crop: 964
  y_crop: 964
  crop_size: 512
  sampling: 'grid'

logging:
  project: NeuralBD
  name: GREGOR

training:
  epochs: 50000
  log_every_n_steps: 100
  name: GREGOR
model:
  dim: 512
  posencoding: True
