base_dir: /gpfs/data/fs71254/schirni/nstack/training/GREGOR_pretrained
meta_state: 'loadme'
data:
  type: 'GREGOR'
  data_path: '/gpfs/data/fs71254/schirni/Level1_Files/hifi_20220602_095015_sd.fts'
  n_images: 50
  pixel_per_ds: 511.5
  x_crop: 964
  y_crop: 964
  crop_size: 256
  psf_type: 'default'

logging:
  project: NeuralBD
  name: GREGOR

training:
  epochs: 10000
  log_every_n_steps: 100
  name: GREGOR_varying
  check_val_every_n_epoch: 10
model:
  dim: 512
  posencoding: True
