base_dir: /gpfs/data/fs71254/schirni/nstack/training/NeuralBD_muram_spatially_varying_interp256_noise_freq256_crop
meta_state: 'none'
data:
  type: 'MURAM'
  data_path: '/gpfs/data/fs71254/schirni/nstack/data/I_out_med.468000'
  n_images: 80
  pixel_per_ds: 511.5
  x_crop: 400
  y_crop: 400
  crop_size: 256
  psf_type: 'default'

logging:
  project: NeuralBD
  name: MURAM

training:
  epochs: 10000
  log_every_n_steps: 100
  name: MURAM
  check_val_every_n_epoch: 10
model:
  dim: 512